// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmquG04ehSmj9vN_F5e7J56dX12oUMpWQ',
    appId: '1:503279961692:web:95ee973af8c11491d44899',
    messagingSenderId: '503279961692',
    projectId: 'ciflutter',
    authDomain: 'ciflutter.firebaseapp.com',
    storageBucket: 'ciflutter.firebasestorage.app',
    measurementId: 'G-HXQWWM0HXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4d5nEQHGjzaJdoVEB9oNVKtxHj3SoWrY',
    appId: '1:503279961692:android:b26bb48d5e0ce585d44899',
    messagingSenderId: '503279961692',
    projectId: 'ciflutter',
    storageBucket: 'ciflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgS16f9kPp_B7y7ZDmnn4ntKiHfgHmUi0',
    appId: '1:503279961692:ios:cc452c847c032910d44899',
    messagingSenderId: '503279961692',
    projectId: 'ciflutter',
    storageBucket: 'ciflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterCi20242025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgS16f9kPp_B7y7ZDmnn4ntKiHfgHmUi0',
    appId: '1:503279961692:ios:cc452c847c032910d44899',
    messagingSenderId: '503279961692',
    projectId: 'ciflutter',
    storageBucket: 'ciflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterCi20242025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmquG04ehSmj9vN_F5e7J56dX12oUMpWQ',
    appId: '1:503279961692:web:3f4591cdab744d54d44899',
    messagingSenderId: '503279961692',
    projectId: 'ciflutter',
    authDomain: 'ciflutter.firebaseapp.com',
    storageBucket: 'ciflutter.firebasestorage.app',
    measurementId: 'G-EP1Q00SP3K',
  );
}
